name: Sync master with upstream latest

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'  # scheduled at 07:00 every Monday and Thursday

jobs:
  sync_with_upstream:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Sync upstream
        uses: aormsby/Fork-Sync-With-Upstream-action@v1
        with:
          upstream_repository: refact0r/midnight-discord
          upstream_branch: master
