on:
  push:
  schedule:
    - cron:  '0 0 2,4,6,8,10,12,14,16,18,20,22,24,26,28 * *'
  workflow_dispatch:


jobs:
  sync_with_upstream:
    runs-on: ubuntu-latest
    name: Sync main with upstream latest

    steps:
    # Step 1: run a standard checkout action, provided by github
    - name: Checkout main
      uses: actions/checkout@v2
      with:
        ref: master
        # submodules: 'recursive'     ### may be needed in your situation

    # Step 2: run this sync action - specify the upstream repo, upstream branch to sync with, and target sync branch
    - name: Pull (Fast-Forward) upstream changes
      id: sync
      uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
      with:
        target_sync_branch: master
        target_repo_token: ${{ secrets.GH_TOKEN }}
        upstream_sync_branch: master
        upstream_sync_repo: refact0r/midnight-discord


    # Step 3: Display a message if 'sync' step had new commits (simple test)
    - name: New commits found
      if: steps.sync.outputs.has_new_commits == 'true'
      run: echo "New commits were found to sync."
    
    - name: No new commits
      if: steps.sync.outputs.has_new_commits == 'false'
      run: echo "There were no new commits."
      
    - name: Show value of 'has_new_commits'
      run: echo ${{ steps.sync.outputs.has_new_commits }}
    # Step 4: Print a helpful timestamp for your records (not required, just nice)
    - name: Timestamp
      run: date
